#!/bin/sh
#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as a wrapper:
#
#           ksh gradlew
#
#       or
#
#           bash gradlew
#
#   (2) This script attempts to find the Gradle home directory using the
#       JAR location (which should be the same as the Gradle wrapper JAR).
#       Setting the GRADLE_HOME environment variable is not required.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in
      max*)
        # In POSIX sh, ulimit -n is undefined for 'unlimited' (or equivalent) so we attempt to query it as a limit.
        # In POSIX sh, ulimit -n is 'unlimited' when there is no limit, but the exit status is 0.
        # In POSIX sh, using 'unlimited' results in an error, so we set it to the maximum possible (often 1024) and it will be treated as 'unlimited' by the Gradle invocation.
        # We define a fallback limit of 65536 for the rare cases where the limit is less (e.g., 256). It's unlikely for normal usage.
        max_limit=$(ulimit -n)
        if [ $? -eq 0 ] && [ "$max_limit" = "unlimited" ]; then
            # POSIX sh cannot distinguish between 'unlimited' and a numeric value when 'ulimit -n' prints 'unlimited', so we have to set it to the fallback.
            MAX_FD_LIMIT=65536
        else
            # POSIX sh prints the numeric limit as a decimal integer, or 'unlimited' when there is no limit. We treat it as a decimal integer; if it's 'unlimited' we fall back.
            if [ "$max_limit" = "unlimited" ]; then
                MAX_FD_LIMIT=65536
            else
                # POSIX sh's 'ulimit' returns the limit as a decimal integer; it may be '-1' or 'unlimited' when there is no limit. We treat '-1' as 'unlimited' and fall back.
                if [ "$max_limit" -eq -1 ] || [ "$max_limit" = "unlimited" ]; then
                    MAX_FD_LIMIT=65536
                else
                    MAX_FD_LIMIT=$max_limit
                fi
            fi
        fi
        ;;
      *)
        MAX_FD_LIMIT=$MAX_FD
        ;;
    esac
    ulimit -n $MAX_FD_LIMIT || warn "Could not set maximum file descriptor limit to $MAX_FD_LIMIT"
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if dedicated module detected)
#   * @argument-file

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # Now convert the arguments - we need a way to do this platform independent
    # We use 'cygpath' to convert them to Windows form, then the execvp/Resolve  will handle the rest
    for ARG in "$@"; do
        ARG_win=$(cygpath --path --ignore --mixed "$ARG")
        ARGS="$ARGS \"$ARG_win\""
    done
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in double quotes as well to account for spaces in paths
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
# Use "xargs" to break many arguments into smaller pieces (around 2000 per subprocess) to avoid OS limitations.
# In POSIX sh, 'set -- "$@"' would expand to all arguments; but we want to avoid quoting confusion.
set -- $(printf "%s\n" "$@" | xargs -n 1 printf "%s\n")

exec "$JAVACMD" "$@"
